ai_models:
  - "gpt-4o-mini"
  - "gemini-1.5-flash"
  - "gpt-4o"
  - "deepseek-r1"
prompt_tone: "не серьёзный, повседневный, при этом уважительный" # Тон ответа в комментарии (должен быть в ковычках) 
comment_limit: 5 # Лимит комментариев на один аккаунт
sleep_duration: 300 # Пауза после достижения лимита комментариев (в секундах) 
join_channel_delay: 1-5 # Задержка перед подпиской на канал (в секундах) 
send_message_delay: 10-20 # Диапазон задержки перед отправкой сообщения
random_prompt: false # Выбор случайного пользовательского промпта (true/false)
detect_language: false # Определять язык поста (true/false) 